import type { TemplateMeta } from ".";

export const agency: TemplateMeta = {
  id: "agency",
  name: "Agency & Business",
  description: "Professional, bold design for agencies, consultancies, and B2B companies.",
  thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop",
  category: "business",
  isPro: true,
  price: 1900,
  sections: [
    { id: "hero", type: "hero", label: "Hero", enabled: true },
    { id: "services", type: "services", label: "Services", enabled: true },
    { id: "about", type: "about", label: "About Us", enabled: true },
    { id: "work", type: "work", label: "Case Studies", enabled: true },
    { id: "team", type: "team", label: "Team", enabled: true },
    { id: "testimonials", type: "testimonials", label: "Testimonials", enabled: true },
    { id: "pricing", type: "pricing", label: "Pricing", enabled: true },
    { id: "contact", type: "contact", label: "Contact", enabled: true },
    { id: "faq", type: "faq", label: "FAQ", enabled: true },
  ],
  defaultTheme: {
    displayFont: "Sora",
    bodyFont: "Source Sans 3",
    headingScale: 1,
    type: {
      heading: { weight: 600, tracking: -0.02, transform: "none" },
      brand: { weight: 700, tracking: 0.08, transform: "none" },
      eyebrow: { size: 11, weight: 600, tracking: 0.24, transform: "uppercase" },
      button: { size: 12, weight: 600, tracking: 0.16, transform: "uppercase" },
      nav: { size: 13, weight: 500, tracking: 0.06, transform: "none" },
      body: { weight: 400, lineHeight: 1.7 },
    },
    colors: {
      sand50: "#f7f7f8", sand100: "#eeeef0", sand200: "#dddee2", sand300: "#c5c6cc", sand400: "#9da0ab",
      clay500: "#6b6e7a", clay600: "#4e5160",
      bark700: "#2d2f3a", bark800: "#1f2028", bark900: "#13141a",
    },
  },
  defaultNav: {
    brand: "YOUR AGENCY",
    tagline: "Digital Solutions",
    links: [
      { label: "Services", href: "#services" },
      { label: "Work", href: "#work" },
      { label: "About", href: "#about" },
      { label: "Team", href: "#team" },
      { label: "Pricing", href: "#pricing" },
    ],
    ctaLabel: "Start a Project",
    ctaHref: "#contact",
  },
  defaultHero: {
    enabled: true,
    media: { type: "image", image: "/images/hero.jpg", video: "", youtube: "" },
    overlay: 50,
    title: "YOUR AGENCY",
    tagline: "Digital Solutions",
    headline: "We build what matters",
    subline: "Strategy, design, and development for brands ready to grow. From concept to launch, we're your partners.",
    primaryLabel: "Start a Project",
    primaryHref: "#contact",
    secondaryLabel: "Our Work",
    secondaryHref: "#work",
    scrollLabel: "Scroll",
  },
};
