import type { TemplateMeta } from ".";

export const blog: TemplateMeta = {
  id: "blog",
  name: "Blog & Magazine",
  description: "Readable, content-first layout for blogs, magazines, and editorial sites.",
  thumbnail: "https://images.unsplash.com/photo-1432821596592-e2c18b78144f?w=600&h=400&fit=crop",
  category: "editorial",
  isPro: true,
  price: 1900,
  sections: [
    { id: "hero", type: "hero", label: "Hero", enabled: true },
    { id: "featured", type: "featured", label: "Featured Posts", enabled: true },
    { id: "categories", type: "categories", label: "Categories", enabled: true },
    { id: "about", type: "about", label: "About", enabled: true },
    { id: "newsletter", type: "newsletter", label: "Newsletter", enabled: true },
    { id: "archive", type: "archive", label: "Recent Posts", enabled: true },
    { id: "contact", type: "contact", label: "Contact", enabled: true },
  ],
  defaultTheme: {
    displayFont: "Lora",
    bodyFont: "Nunito Sans",
    headingScale: 1,
    type: {
      heading: { weight: 500, tracking: -0.01, transform: "none" },
      brand: { weight: 600, tracking: 0.1, transform: "none" },
      eyebrow: { size: 10, weight: 600, tracking: 0.28, transform: "uppercase" },
      button: { size: 11, weight: 600, tracking: 0.2, transform: "uppercase" },
      nav: { size: 12, weight: 600, tracking: 0.1, transform: "none" },
      body: { weight: 400, lineHeight: 1.8 },
    },
    colors: {
      sand50: "#faf9f7", sand100: "#f2f0eb", sand200: "#e6e2d9", sand300: "#d4cec2", sand400: "#b5ad9c",
      clay500: "#8a7e6a", clay600: "#6b6050",
      bark700: "#3a3428", bark800: "#28241c", bark900: "#1a1712",
    },
  },
  defaultNav: {
    brand: "YOUR BLOG",
    tagline: "Stories & Ideas",
    links: [
      { label: "Latest", href: "#featured" },
      { label: "Categories", href: "#categories" },
      { label: "About", href: "#about" },
      { label: "Contact", href: "#contact" },
    ],
    ctaLabel: "Subscribe",
    ctaHref: "#newsletter",
  },
  defaultHero: {
    enabled: true,
    media: { type: "image", image: "/images/hero.jpg", video: "", youtube: "" },
    overlay: 40,
    title: "YOUR BLOG",
    tagline: "Stories & Ideas",
    headline: "Words that stay with you",
    subline: "Thoughtful writing on design, culture, and the things that shape how we see the world.",
    primaryLabel: "Start Reading",
    primaryHref: "#featured",
    secondaryLabel: "Subscribe",
    secondaryHref: "#newsletter",
    scrollLabel: "Scroll",
  },
};
