import type { TemplateMeta } from ".";

export const resort: TemplateMeta = {
  id: "resort",
  name: "Resort & Hospitality",
  description: "Warm, luxurious feel for boutique resorts, hotels, and vacation rentals.",
  thumbnail: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&h=400&fit=crop",
  category: "hospitality",
  isPro: false,
  price: 0,
  sections: [
    { id: "hero", type: "hero", label: "Hero", enabled: true },
    { id: "about", type: "about", label: "About", enabled: true },
    { id: "amenities", type: "amenities", label: "Amenities", enabled: true },
    { id: "gallery", type: "gallery", label: "Gallery", enabled: true },
    { id: "rooms", type: "rooms", label: "Rooms & Suites", enabled: true },
    { id: "testimonials", type: "testimonials", label: "Testimonials", enabled: true },
    { id: "location", type: "location", label: "Location", enabled: true },
    { id: "contact", type: "contact", label: "Contact", enabled: true },
    { id: "faq", type: "faq", label: "FAQ", enabled: true },
  ],
  defaultTheme: {
    displayFont: "Cormorant Garamond",
    bodyFont: "Jost",
    headingScale: 1,
    type: {
      heading: { weight: 300, tracking: -0.01, transform: "none" },
      brand: { weight: 300, tracking: 0.16, transform: "none" },
      eyebrow: { size: 10, weight: 400, tracking: 0.32, transform: "uppercase" },
      button: { size: 11, weight: 400, tracking: 0.24, transform: "uppercase" },
      nav: { size: 11, weight: 400, tracking: 0.22, transform: "uppercase" },
      body: { weight: 300, lineHeight: 1.9 },
    },
    colors: {
      sand50: "#fbf9f5", sand100: "#f5f0e7", sand200: "#ebe3d5", sand300: "#dbcfba", sand400: "#c4b092",
      clay500: "#a08863", clay600: "#7d6748",
      bark700: "#4a4034", bark800: "#332d25", bark900: "#221e19",
    },
  },
  defaultNav: {
    brand: "YOUR RESORT",
    tagline: "Boutique Beachfront Retreat",
    links: [
      { label: "About", href: "#about" },
      { label: "Rooms", href: "#rooms" },
      { label: "Gallery", href: "#gallery" },
      { label: "Location", href: "#location" },
      { label: "FAQ", href: "#faq" },
    ],
    ctaLabel: "Book Now",
    ctaHref: "#contact",
  },
  defaultHero: {
    enabled: true,
    media: { type: "image", image: "/images/hero.jpg", video: "", youtube: "" },
    overlay: 45,
    title: "YOUR RESORT",
    tagline: "Boutique Beachfront Retreat",
    headline: "Where the ocean meets serenity",
    subline: "An intimate escape on pristine shores — designed for travelers who seek beauty, silence, and discovery.",
    primaryLabel: "Book Your Stay",
    primaryHref: "#contact",
    secondaryLabel: "Explore",
    secondaryHref: "#about",
    scrollLabel: "Scroll",
  },
};
