import type { TemplateMeta } from ".";

export const restaurant: TemplateMeta = {
  id: "restaurant",
  name: "Restaurant & Cafe",
  description: "Inviting palette for restaurants, cafes, bakeries, and food businesses.",",
  thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
  category: "food",
  isPro: false,
  price: 0,
  sections: [
    { id: "hero", type: "hero", label: "Hero", enabled: true },
    { id: "story", type: "story", label: "Our Story", enabled: true },
    { id: "menu", type: "menu", label: "Menu", enabled: true },
    { id: "gallery", type: "gallery", label: "Gallery", enabled: true },
    { id: "chef", type: "chef", label: "Meet the Chef", enabled: true },
    { id: "reviews", type: "reviews", label: "Reviews", enabled: true },
    { id: "hours", type: "hours", label: "Hours & Location", enabled: true },
    { id: "reservations", type: "reservations", label: "Reservations", enabled: true },
  ],
  defaultTheme: {
    displayFont: "Playfair Display",
    bodyFont: "DM Sans",
    headingScale: 1,
    type: {
      heading: { weight: 400, tracking: -0.01, transform: "none" },
      brand: { weight: 400, tracking: 0.18, transform: "none" },
      eyebrow: { size: 10, weight: 500, tracking: 0.3, transform: "uppercase" },
      button: { size: 11, weight: 500, tracking: 0.2, transform: "uppercase" },
      nav: { size: 12, weight: 500, tracking: 0.12, transform: "none" },
      body: { weight: 400, lineHeight: 1.8 },
    },
    colors: {
      sand50: "#faf8f5", sand100: "#f3ede4", sand200: "#e6ddd0", sand300: "#d5c8b5", sand400: "#bfab93",
      clay500: "#b07a4f", clay600: "#8a5c35",
      bark700: "#3d2e1e", bark800: "#2a1f14", bark900: "#1a130c",
    },
  },
  defaultNav: {
    brand: "YOUR KITCHEN",
    tagline: "Farm to Table",
    links: [
      { label: "Menu", href: "#menu" },
      { label: "Story", href: "#story" },
      { label: "Gallery", href: "#gallery" },
      { label: "Hours", href: "#hours" },
    ],
    ctaLabel: "Reserve a Table",
    ctaHref: "#reservations",
  },
  defaultHero: {
    enabled: true,
    media: { type: "image", image: "/images/hero.jpg", video: "", youtube: "" },
    overlay: 40,
    title: "YOUR KITCHEN",
    tagline: "Farm to Table",
    headline: "Every dish tells a story",
    subline: "Seasonal ingredients, honest cooking, and a space where friends gather around the table.",
    primaryLabel: "View Menu",
    primaryHref: "#menu",
    secondaryLabel: "Reserve",
    secondaryHref: "#reservations",
    scrollLabel: "Scroll",
  },
};
